### PR TITLE
Implicitly add an npm dev dependency on bower

### LINKED ISSUE #141: ember-cli module directory emptied of files
When using a `yarn.lock` but without bower as a dependency in `package.json`, the `node_modules/ember-cli/` is emptied of files.

* Failed build with error: https://circleci.com/gh/Vestorly/torii/614
* Successful build: https://circleci.com/gh/Vestorly/torii/615 
* Only change to fix was adding bower to `package.json`: https://github.com/Vestorly/torii/pull/382/commits/43d9737b617a5a555b5d325e23fe7ad23961997f

Currently when `yarn` is detected ember-try attempts to use it for most operations. An exception is that if bower is not a dependency, `npm` is used to install that dependency. I presume there is some negative interaction between the two systems that causes the files to be deleted.

### LINKED ISSUE #150: Scenarios missing their deps when no bower and no package-lock.json
If your app does not have bower and does not have a package-lock.json, it's possible to get into a state where `ember-try` installs `bower` while accidentally producing a package-lock.json that *only* contains bower. 

Then apparently during scenario setup it respects the package-lock.json and you end up missing all your packages.

### PR DESCRIPTION
**Pull request by hjdivad**
For scenarios that
 1. do not already have a dependency or dev dependency on bower and
 2. have bower dependencies

Also assert that
 1. npm is ran before bower
 2. if bower is run, a local bower is found

This PR is a continuation of, and supersedes, #151.
Fixes #141 
Fixes #150

### CODE REVIEW

File: lib/dependency-manager-adapters/bower.js [hunk 1]
```diff
@@ -172,26 +175,13 @@ module.exports = CoreObject.extend({
...
-      })
-      .then(function(bowerPath) {
-        return '"' + path.join(bowerPath, '..', '..', 'bin', 'bower') + '"';
-      });
-  },
-  _installBower: function() {
-    var adapter = this;
-    debug('Installing bower via npm');
-    return adapter.run('npm', [].concat(['install', 'bower@^1.3.12']), { cwd: adapter.cwd });
+    return findEmberPath(adapter.cwd).then(function(emberPath) {
```
Comment (kategengler) [inline lib/dependency-manager-adapters/bower.js]: I know you didn't add this, but I wonder if finding bower relative to ember-cli is necessary anymore?

Comment (hjdivad) [reply lib/dependency-manager-adapters/bower.js]: @kategengler hmm good point.  So presumably the logic would be

1. run npm before bower
2. trust that bower exists in `PROJECT_ROOT/node_modules/.bin/bower` and assert otherwise

Comment (kategengler) [reply lib/dependency-manager-adapters/bower.js]: Yeah, or we can just leave this since it works, but just thought it worth thinking about

Comment (hjdivad) [reply lib/dependency-manager-adapters/bower.js]: @kategengler leaving it in this PR seems like the right thing to do; it'll be easier to track & revert in a separate PR if it causes issues (although I think you're right that finding it relative to ember-cli would no longer be useful).

**Comment by rwjblue** [comment]
OK, one of the CI jobs (the `client-test` job) failed for:

> The job exceeded the maximum time limit for jobs, and has been terminated.

Seemed bizarre (since that job took only 12 minutes on the last merge), I restarted it...

**Comment by kategengler** [comment]
Ah, most of the scenarios in client-test were only using bower, but with this PR they will each be npm installing, which could account for the huge increase in time. Might be worth rethinking client-test; I think we can remove most of the deprecated commands, at the very least.

**Comment by rwjblue** [comment]
OK, I removed deprecated commands in 9f10230 (please double check me 😄). 

Hoping this shortened things up enough...

**Comment by kategengler** [comment]
So did I in https://github.com/ember-cli/ember-try/pull/160

**Comment by rwjblue** [comment]
Shoot, sorry. I didn’t check my GH notifications before updating...
